const fs = require('fs').promises;
const path = require('path');
const { v4: uuidv4 } = require('uuid');

class DocumentService {
  constructor() {
    this.uploadsDir = path.join(__dirname, '..', 'uploads');
    this.ensureUploadsDir();
  }

  async ensureUploadsDir() {
    try {
      await fs.access(this.uploadsDir);
    } catch {
      await fs.mkdir(this.uploadsDir, { recursive: true });
    }
  }

  async generateWordDocument(content, clientName, reportPeriod) {
    try {
      // For now, we'll create a simple text file that can be converted to Word
      // In production, you'd use a library like officegen or docx
      
      const filename = `${clientName.replace(/\s+/g, '_')}_${reportPeriod.replace(/\s+/g, '_')}_${uuidv4()}.txt`;
      const filepath = path.join(this.uploadsDir, filename);
      
      const documentContent = this.formatDocumentContent(content, clientName, reportPeriod);
      
      await fs.writeFile(filepath, documentContent, 'utf8');
      
      return {
        filename,
        filepath,
        url: `/uploads/${filename}`
      };
    } catch (error) {
      console.error('Document generation error:', error);
      throw new Error('Failed to generate document');
    }
  }

  formatDocumentContent(content, clientName, reportPeriod) {
    const header = `
MONTHLY STATUS REPORT
=====================

CLIENT NAME: ${clientName}
REPORTING PERIOD: ${reportPeriod}
GENERATED: ${new Date().toLocaleDateString()}

${'-'.repeat(60)}

`;

    const footer = `

${'-'.repeat(60)}

This report was generated by the TEG Report Management System.
For questions or clarifications, please contact your account representative.

Generated on: ${new Date().toLocaleString()}
`;

    return header + content + footer;
  }

  async getDocument(filename) {
    try {
      const filepath = path.join(this.uploadsDir, filename);
      const content = await fs.readFile(filepath, 'utf8');
      return content;
    } catch (error) {
      console.error('Error reading document:', error);
      throw new Error('Document not found');
    }
  }

  async deleteDocument(filename) {
    try {
      const filepath = path.join(this.uploadsDir, filename);
      await fs.unlink(filepath);
      return true;
    } catch (error) {
      console.error('Error deleting document:', error);
      return false;
    }
  }
}

module.exports = new DocumentService();
