const fs = require('fs').promises;
const path = require('path');

class DocumentService {
  constructor() {
    this.uploadsDir = path.join(__dirname, '..', 'uploads');
    this.ensureUploadsDir();
  }

  async ensureUploadsDir() {
    try {
      await fs.access(this.uploadsDir);
    } catch {
      await fs.mkdir(this.uploadsDir, { recursive: true });
    }
  }

  async generateTextDocument(content, clientName, reportPeriod) {
    try {
      const timestamp = new Date().toISOString().split('T')[0];
      const filename = `${clientName.replace(/\s+/g, '_')}_${reportPeriod.replace(/\s+/g, '_')}_${timestamp}.txt`;
      const filepath = path.join(this.uploadsDir, filename);
      
      const documentContent = this.formatDocumentContent(content, clientName, reportPeriod);
      
      await fs.writeFile(filepath, documentContent, 'utf8');
      
      return {
        filename,
        filepath,
        url: `/uploads/${filename}`
      };
    } catch (error) {
      console.error('Document generation error:', error);
      return {
        filename: 'report.txt',
        filepath: '',
        url: '/uploads/report.txt'
      };
    }
  }

  formatDocumentContent(content, clientName, reportPeriod) {
    const header = `
MONTHLY STATUS REPORT
=====================

CLIENT NAME: ${clientName}
REPORTING PERIOD: ${reportPeriod}
GENERATED: ${new Date().toLocaleDateString()}

${'-'.repeat(60)}

`;

    const footer = `

${'-'.repeat(60)}

This report was generated by the TEG Report Management System.
For questions or clarifications, please contact your account representative.

Generated on: ${new Date().toLocaleString()}
`;

    return header + content + footer;
  }
}

module.exports = new DocumentService();
